blank_issues_enabled: true
contact_links:
  - name: Submit a resource type
    url: https://github.com/concourse/resource-types
    about: if you want to submit or request a resource type.
  - name: Visit the resource types website
    url: https://resource-types.concourse-ci.org
    about: Click open to visit the live website.
